apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/philstar79/environment-philstar-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: midyear-gift-242620
    envOrganisation: philstar79@gmail.com
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: philstar79@gmail.com
    promotionEngine: Prow
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://philstar-lts-e5e4ca64-5cc3-45b9-9930-a77cb0b264de
      classifier: default
    - bucketUrl: gs://philstar-lts-e5e4ca64-5cc3-45b9-9930-a77cb0b264de
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
